import React from 'react'
import "./Navbar.css"
import Products from '../data/Products'
import { useNavigate } from 'react-router'



const Product = () => {

    const navigate = useNavigate();

    const handleVR = (id,name) => {    
        navigate("/productVR",{state:{id:id,product:name}})
    }
    const handleAR = (id,name) => {    
        navigate("/productAR",{state:{id:id,product:name}})
    }
    const handleTransaction = (id,name,price) => {    
        navigate("/payment",{state:{id:id,product:name,price:price}})
    }
    
  return (
    <div>
        <section id='Hero'>
        <div className="row">
    {Products.map((item)=>{
       return( <div className="sec col-lg-6 col-md-6 col-sm-12">
        <h4><b>{item.name}</b></h4><img src={item.image} className="ps4" alt="No image" /><ul>
            <br />
            <li><p><small>{item.info1}</small></p></li>
            <li><p><small>{item.info2}</small></p> </li>
            <li><p><small>{item.info3}</small></p> </li>
            <li><p><small>{item.info4}</small></p> </li>
            <li><h6><b>PRICE:<b>{item.price}</b></b></h6></li>
            <div className='btnStyle'>
            <button className="btn btn-warning btn-sm buy" onClick={()=>{handleTransaction(item.id,item.name,item.price)}}>BUY NOW</button>
            <button className="btn btn-warning btn-sm buy" onClick={()=>{handleVR(item.id,item.name)}}>VR</button>
            <button className="btn btn-warning btn-sm buy" onClick={()=>{handleAR(item.id,item.name)}}>AR</button>  
            </div>
            <br />
        </ul>
         </div>
    )})}
         </div>
         </section>
        
        </div>
  )
}

export default Product






/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pratibha (https://sketchfab.com/Camay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-set-b87c52f6f86642dc8c7bc8e321ac3a7b
Title: Sofa Set
*/

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";

// export function Model(props) {
//   const { nodes, materials } = useGLTF("/sofa_set.glb");
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_2.geometry}
//           material={materials["Material.001"]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_3.geometry}
//           material={materials["Material.001"]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_4.geometry}
//           material={materials["Material.001"]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_5.geometry}
//           material={materials["Material.001"]}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/sofa_set.glb");




/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: chris_models (https://sketchfab.com/chris_models)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-classic-furniture-set-dfbfbf514a3943939b2ffad7c4571099
Title: Sofa - Classic furniture set.
*/



/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: artvolodskikh (https://sketchfab.com/artvolodskikh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-chair-a7fefb5dde954c84896949246dde5be6
Title: Office Chair
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: QuarizonStudio (https://sketchfab.com/QuarizonStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-living-room-3ac5d18326e24a1ab47279466e4e00ad
Title: vintage living room
*/


